// <auto-generated />
namespace TPTwo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class newtext_fbprofile_createdatestring : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newtext_fbprofile_createdatestring));
        
        string IMigrationMetadata.Id
        {
            get { return "201702070025175_newtext_fbprofile_createdatestring"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
