// <auto-generated />
namespace TPTwo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class theIDforThinkingOfYou : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(theIDforThinkingOfYou));
        
        string IMigrationMetadata.Id
        {
            get { return "201702152219535_theID for ThinkingOfYou"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
