// <auto-generated />
namespace TPTwo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class InQuestions_add_theFBID_remove_Icollection : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InQuestions_add_theFBID_remove_Icollection));
        
        string IMigrationMetadata.Id
        {
            get { return "201702151938449_InQuestions_add_theFBID_remove_Icollection"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
